---
# roles/mysql/tasks/mysql.yml
- name: set mysql.repo
  yum: name="http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm"
       update_cache=yes
  tags: 
    - mysql

- name: Install mysql
  yum: name=mysql-community-server state=present
  tags: 
    - mysql

- name: be sure mysqld is running and enabled
  service: name=mysqld state=started enabled=yes
  tags:
    - mysql

- name: set root pass
  mysql_user: name=root host="{{item}}" password={{ mysql_root_db_pass }}
  with_items:
    - 127.0.0.1
    - localhost
  tags: 
    - mysql

- name: set /etc/my.cnf
  copy: src=my.cnf dest=/etc/my.cnf owner=root mode=0644
  register: mod_mycnf
  tags: 
    - mysql

- name: be sure mysqld is running and enabled
  service: name=mysqld state=restarted
  when: mod_mycnf.changed
  tags:
    - mysql

- name: set .my.cnf
  template: src=local_my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  tags: 
    - mysql
